# Generated by Django 5.2.8 on 2025-11-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_holiday_companyleavepolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('company', 'date')},
        ),
    ]
