# Generated by Django 5.2.8 on 2025-11-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_holiday_options_holiday_is_optional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='holiday',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=list)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
    ]
