# Generated by Django 5.2.8 on 2025-11-11 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_holiday_options_alter_holiday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='email_draft',
            field=models.TextField(blank=True, help_text='AI-generated email draft sent by employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='proof_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='proof_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='proof_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='proof_requested_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
