# Generated by Django 5.2.8 on 2025-11-11 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_leaverequest_email_draft_leaverequest_proof_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Company is properly registered and verified'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanyRoleDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address that should be assigned this role', max_length=254)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin')], default='employee', help_text='Role to assign when this email signs up', max_length=20)),
                ('designated_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_designations', to='core.company')),
                ('designated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Designation',
                'verbose_name_plural': 'Role Designations',
                'unique_together': {('company', 'email')},
            },
        ),
    ]
