# Generated by Django 5.2.8 on 2025-11-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_company_is_verified_company_registered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
